# Generated by Django 6.0.4 on 2026-05-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('video_file', models.FileField(upload_to='media/videos/')),
                ('thumbnail', models.ImageField(upload_to='media/thumbnails/')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
