# Generated by Django 6.0.4 on 2026-05-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_master_playlist',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
