# Generated by Django 6.0.4 on 2026-05-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0006_alter_video_hls_master_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hls_master_playlist',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
