# Generated by Django 5.2.14 on 2026-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0008_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional. Wird automatisch aus dem Video erstellt.', null=True, upload_to='thumbnails/'),
        ),
    ]
