# Generated by Django 5.2.13 on 2026-05-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0009_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animation', 'Animation'), ('anime', 'Anime'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('documentary', 'Documentary'), ('drama', 'Drama'), ('family', 'Family'), ('fantasy', 'Fantasy'), ('history', 'History'), ('horror', 'Horror'), ('kids', 'Kids'), ('mystery', 'Mystery'), ('nature', 'Nature'), ('reality', 'Reality'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi'), ('sports', 'Sports'), ('thriller', 'Thriller'), ('war', 'War'), ('western', 'Western')], default='action', max_length=50),
        ),
    ]
